### ISSUE TITLE
support instance principal, then no need to config api key config file

### ISSUE THREAD

**Issue by munger1985** [jin38324/OCI_GenAI_access_gateway#1]

**Comment by munger1985** [comment]
see also https://github.com/jin38324/OCI_GenAI_access_gateway/pull/2

**Comment by munger1985** [comment]
hi，JG，供你参考，不一定要merge，我已经在我fork的你的项目改了，可以。方便。

**Comment by munger1985** [comment]
你这个项目的语法写得太赞了。

**Comment by jin38324** [comment]
New feature added by merging your pull request.
